---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment # necessary for Kustomize identification
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      nodeSelector:
        env: stg
