---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  env: stage

resources:
  - configmap.yaml

namespace: stage

patchesStrategicMerge:
  - deployment.yaml
